
logging:
  level:
    com.naztuo: debug
  file: E:\\log\miaosha.log
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/miaosha?serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.naztuo.user.bean,com.naztuo.miaosha.bean
  configuration:
    map-underscore-to-camel-case: true
  config-locations: classpath:mybatis/mybatis-config.xml

